### ISSUE TITLE
Having an issue with the plugin starting up.

### ISSUE THREAD

**Issue by ItsWavvy** [maurxce/PaidPortals#1]
This is what the console is outputting:

09.03 02:54:35 [Server] [WARN] Enabled plugin with unregistered ConfiguredPluginClassLoader PaidPortals v1.1
09.03 02:54:35 [Server] [ERROR] Error occurred while enabling PaidPortals v1.1 (Is it up to date?)
09.03 02:54:35 [Server] [INFO] java.lang.NullPointerException: null
09.03 02:54:35 [Server] [INFO] at java.io.Reader.<init>(Reader.java:168) ~[?:?]
09.03 02:54:35 [Server] [INFO] at java.io.InputStreamReader.<init>(InputStreamReader.java:76) ~[?:?]
09.03 02:54:35 [Server] [INFO] at me.maurxce.paidportals.managers.FileManager.getDbMessages(FileManager.java:72) ~[PaidPortals-1.1.jar:?]
09.03 02:54:35 [Server] [INFO] at me.maurxce.paidportals.dao.YAML.<init>(YAML.java:17) ~[PaidPortals-1.1.jar:?]
09.03 02:54:35 [Server] [INFO] at me.maurxce.paidportals.managers.DatabaseManager.setupDatabase(DatabaseManager.java:20) ~[PaidPortals-1.1.jar:?]
09.03 02:54:35 [Server] [INFO] at me.maurxce.paidportals.Main.onEnable(Main.java:20) ~[PaidPortals-1.1.jar:?]

**Comment by ItsWavvy** [comment]
Solved. Needed PlaceholderAPI!
